services:
  db_fonte:
    image: postgres:16
    container_name: db_fonte
    environment:
      POSTGRES_USER: wind_etl
      POSTGRES_PASSWORD: wind_etl
      POSTGRES_DB: fonte
    ports:
      - "5433:5432"
    volumes:
      - db_fonte_data:/var/lib/postgresql/data
    networks:
      - wind_etl_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wind_etl -d fonte"]
      interval: 5s
      timeout: 5s
      retries: 10


  db_alvo:
    image: postgres:16
    container_name: db_alvo
    environment:
      POSTGRES_USER: wind_etl
      POSTGRES_PASSWORD: wind_etl
      POSTGRES_DB: alvo
    ports:
      - "5434:5432"
    volumes:
      - db_alvo_data:/var/lib/postgresql/data
    networks:
      - wind_etl_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wind_etl -d alvo"]
      interval: 5s
      timeout: 5s
      retries: 10

  db_init:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: db_init
    depends_on:
      db_fonte:
        condition: service_healthy
      db_alvo:
        condition: service_healthy
    environment:
      - DB_FONTE_DSN=postgresql://wind_etl:wind_etl@db_fonte:5432/fonte
      - DB_ALVO_DSN=postgresql://wind_etl:wind_etl@db_alvo:5432/alvo
    networks:
      - wind_etl_network
    command: ["python", "-m", "src.scripts.init_databases"]

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: wind_etl_api
    depends_on:
      db_fonte:
        condition: service_healthy
      db_init:
        condition: service_completed_successfully
    environment:
      - DB_FONTE_DSN=postgresql://wind_etl:wind_etl@db_fonte:5432/fonte
    ports:
      - "8000:8000"
    networks:
      - wind_etl_network

  dagster:
    build:
      context: .
      dockerfile: Dockerfile.dagster
    container_name: wind_etl_dagster
    depends_on:
      db_fonte:
        condition: service_healthy
      db_alvo:
        condition: service_healthy
      api:
        condition: service_started
    environment:
      - DB_FONTE_DSN=postgresql://wind_etl:wind_etl@db_fonte:5432/fonte
      - DB_ALVO_DSN=postgresql://wind_etl:wind_etl@db_alvo:5432/alvo
      - CONECTOR_API_URL=http://api:8000
    ports:
      - "3000:3000"
    networks:
      - wind_etl_network

volumes:
  db_fonte_data:
  db_alvo_data:

networks:
  wind_etl_network:
    driver: bridge
